name: orb
version: 4.7
date: 31/04/2014
description: Methods to enumerate Orbits

authors:
    - name: Juergen Mueller
      url: http://www.math.rwth-aachen.de/~Juergen.Mueller
    - name: Max Neunhoeffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske

maintainers:
    - name: Juergen Mueller
      url: http://www.math.rwth-aachen.de/~Juergen.Mueller
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske

GAP: ">=4.4.12"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

suggested-pkgs:
    - name: "IO"
      version: ">= 3.3"
      url: "http://neunhoef.github.io/io/"

www: http://neunhoef.github.io/orb/
readme: http://neunhoef.github.io/orb/README
packageinfo: http://neunhoef.github.io/orb/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/neunhoef/orb/releases/download/v4.7/orb-4.7.tar.gz
    - name: .tar.bz2
      url: https://github.com/neunhoef/orb/releases/download/v4.7/orb-4.7.tar.bz2

abstract: The <span class="pkgname">orb</span> package is about enumerating orbits in various ways.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
