name: orb
version: 4.7.6
date: 08/03/2016
description: |
    Methods to enumerate Orbits

authors:
    - name: Juergen Mueller
      url: http://www.math.rwth-aachen.de/~Juergen.Mueller
    - name: Max Neunhöffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske

maintainers:
    - name: Juergen Mueller
      url: http://www.math.rwth-aachen.de/~Juergen.Mueller
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">=4.6"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

suggested-pkgs:
    - name: "IO"
      version: ">= 3.3"
      url: "https://gap-packages.github.io/io"

www: https://gap-packages.github.io/orb
readme: README
packageinfo: https://gap-packages.github.io/orb/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/orb/releases/download/v4.7.6/orb-4.7.6.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/orb/releases/download/v4.7.6/orb-4.7.6.tar.bz2

abstract: |
    The <span class="pkgname">orb</span> package is about enumerating orbits in various ways.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
