name: orb
version: 4.8.1
date: 2018-09-10
description: |
    Methods to enumerate orbits

authors:
    - name: Juergen Mueller
      url: http://www.math.rwth-aachen.de/~Juergen.Mueller
    - name: Max Neunhöffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske

maintainers:
    - name: Juergen Mueller
      url: http://www.math.rwth-aachen.de/~Juergen.Mueller
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">=4.9"

suggested-pkgs:
    - name: "IO"
      version: ">= 3.3"
      url: "https://gap-packages.github.io/io"

www: https://gap-packages.github.io/orb
readme: README.md
packageinfo: https://gap-packages.github.io/orb/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/orb/releases/download/v4.8.1/orb-4.8.1.tar.gz

abstract: |
    The <span class="pkgname">orb</span> package is about enumerating orbits in various ways.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
