name: orb
version: 4.6
date: 02/05/2013
description: orb - Methods to enumerate Orbits

authors:
    - name: Juergen Mueller
      url: http://www.math.rwth-aachen.de/~Juergen.Mueller
    - name: Max Neunhoeffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske

maintainers:
    - name: Juergen Mueller
      url: http://www.math.rwth-aachen.de/~Juergen.Mueller
    - name: Max Neunhoeffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske

GAP: ">=4.4.12"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"

suggested-pkgs:
    - name: "IO"
      version: ">= 3.3"

www: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/orb.html
readme: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/orb/README.orb
packageinfo: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/orb/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/orb/orb-4.6.tar.gz

abstract: The <span class="pkgname">orb</span> package is about enumerating orbits in various ways.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
